[programs.localnet]
spltoken = "7gAmGKpULv13sfCWchTjx1tbgFxshrN334yyQHM8xpK8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/swarnab/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
